### ISSUE TITLE
No boxart/Cover

### ISSUE THREAD

**Issue by chronoss09** [XboxUnity/AuroraAssetEditor#10]
Hi !!!

i need to add boxart and others on my xbox but nothing working.... AAE give me nothing and nothing to on my xbox....

**Comment by Swizzy** [comment]
You're also giving us absolutely nothing to work with, please be more descriptive of the issue you're facing so we can look into fixing it.

For example, what version are you using? what method of transfer are you using?

**Comment by chronoss09** [comment]
Sorry, i think i use an old version [Aurora Asset Editor v1.3.3](https://github.com/XboxUnity/AuroraAssetEditor/releases/tag/v1.3.3)

Let me check with the last version...

**Comment by Swizzy** [comment]
Try explaining the steps you take when you encounter the issue aswell

**Comment by chronoss09** [comment]
ok thanks a lot and so sorry !!!

**Comment by chronoss09** [comment]
I test the last version and all assets working but no boxart on all game :(
![Capture d'écran 2023-10-27 093513](https://github.com/XboxUnity/AuroraAssetEditor/assets/17669980/3bfc447d-362a-4bb5-86f6-f9f7ef07a8a9)
![Capture d'écran 2023-10-27 093557](https://github.com/XboxUnity/AuroraAssetEditor/assets/17669980/066a0e4b-7dd7-423c-a8da-4304bbaf821f)
![Capture d'écran 2023-10-27 093618](https://github.com/XboxUnity/AuroraAssetEditor/assets/17669980/1a27997c-d22f-449e-a413-5ca3aa25963b)

![Capture d'écran 2023-10-27 093649](https://github.com/XboxUnity/AuroraAssetEditor/assets/17669980/d55e5876-5b1f-4e6b-9f0e-bbb9413bf328)
![Capture d'écran 2023-10-27 093900](https://github.com/XboxUnity/AuroraAssetEditor/assets/17669980/ac1571d7-c33b-45b0-a3ff-b55073b5ee31)

**Comment by Swizzy** [comment]
Unfortunately, they're simply not available for all versions of all games i guess. This isn't a issue with the app itself, it's a issue with the sources used such as the Xbox Marketplace and/or XboxUnity.

The app looks for what it can, but there are no guarantees that something can be found. Since this isn't a issue with the app, i'm going to close this. If you need help finding covers/boxart etc. you need to turn to a forum such as RMS and ask around there.

**Comment by chronoss09** [comment]
XboxUnity is not inaccessible, i think it's a problem...
