### ISSUE TITLE
auto-resize doesn't work?

### ISSUE THREAD

**Issue by ClaireCJS** [XboxUnity/AuroraAssetEditor#18]
So i did manage to update one image manually. I googled for the image, saved it, and added it as a cover.

It is the only image to ever correctly display inside of AuroraAssetEditor on my machine

It successfully updated, yay.  It kept asking me for the TitleID without any explanation why (like, is it forgetting which game is selected and currently on the screen? I don't get it). Me and the other person here were both quite confused, we had to get a piece of paper out and write down the id because they weren't copyable to the clipboard (that felt sadistic), then manually type it in, only to have it fail and not update.

But somehow eventually we realized the save-cover-art-only menu item doesn't ask those unnecessary questions and actually works

But alas, it did not correctly display in Aurora. Even though i have "resize image" checked, I think the aspect ratio was different, and so the cover actually is bigger than the cover and you don't see it all.

**Comment by ClaireCJS** [comment]
here it is :)

it "looked like a cover" so i chose it. only one i could find on google for this game haha.

![image](https://github.com/XboxUnity/AuroraAssetEditor/assets/789591/42bef7c8-c78f-41be-a537-f19028358193)

**Comment by Swizzy** [comment]
When i tested the image it does work, however it gets stretched significantly because it's only 1 of 3 expected pieces.

Aurora expects the image to have a Front, a Spine and a Back - the total size of the expected image is 600x900, where the width of all 3 pieces are 900 pixels - the spine isn't nearly as big as the other two parts - i don't know the measurements of each part myself unfortunately, but you should be able to download pretty much any cover for any game from XboxUnity.net and measure from there.

![image](https://github.com/XboxUnity/AuroraAssetEditor/assets/1915633/a758fbfd-54df-4b17-9b69-c19889114340)

![image](https://github.com/XboxUnity/AuroraAssetEditor/assets/1915633/299958ba-3c6d-414a-8bab-54a22a1d7cb6)

**Comment by Swizzy** [comment]
I looked up the template i remember there being, you can still find it available for download from here; https://www.realmodscene.com/index.php?/topic/6464-making-your-own-covers-the-easy-way/&tab=comments#comment-54975 you'll need Photoshop to use what has been shared tho.
